import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useRouter } from "next/router";

const FetchingDynamic = dynamic(
  () => {
    const mod = import("./component/ShopFetching").then((data) => {
      console.log({ data });
      return data;
    });
    return mod;
  },
  {
    ssr: false,
    loading: () => <>Loading...</>,
  }
);

export default function Home() {
  const router = useRouter();
  console.log({ router });
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href={`/item/121`}>121</Link>
        <Link href={`item/122`}>122</Link>
      </div>
      <div style={{ height: "50vh", overflow: "auto" }}>
        <FetchingDynamic />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
